name: Post Remaining Days of Ummath

on:
  schedule:
    - cron: '0 9 * * *' 
  workflow_dispatch:  

jobs:
  post-ummath:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2 
        with:
          python-version: '3.x' # Choose your desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy requests_oauthlib

      - name: List files 
        run: ls -la

      - name: Calculate Remaining Days and Years
        id: calculate_days
        # ... (rest of your calculation code)

      - name: Post to Twitter
        run: |
          echo "TWITTER_CLIENT_ID=${{ secrets.TWITTER_CLIENT_ID }}" >> $GITHUB_ENV
          echo "TWITTER_CLIENT_SECRET=${{ secrets.TWITTER_CLIENT_SECRET }}" >> $GITHUB_ENV
          python postTweet.py # Assuming you renamed your script to postTweet.py
