name: Post Remaining Days of Ummath (Tweepy)

on:
  schedule:
    - cron: '0 9 * * *'  # Run daily at 09:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  post-ummath:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Or your preferred version

      - name: Install dependencies
        run: pip install tweepy

      - name: Calculate Remaining Days and Years
        id: calculate_days
        run: |
          # Current date
          current_date=$(date +%Y-%m-%d)
          # End date for Ummath 2080
          end_date="2080-09-04"

          # Calculate remaining days using Python
          python << EOF
          import datetime

          current_date = datetime.datetime.strptime("$current_date", "%Y-%m-%d").date()
          end_date = datetime.datetime.strptime("$end_date", "%Y-%m-%d").date()
          remaining_days = (end_date - current_date).days

          print(f"::set-output name=remaining_days::{remaining_days}")
          EOF

      - name: Post to Twitter
        run: |
          python - << EOF
          import tweepy
          import os

          def post_tweet(api_key, api_secret, access_token, access_token_secret, message):
              auth = tweepy.OAuthHandler(api_key, api_secret)
              auth.set_access_token(access_token, access_token_secret)
              api = tweepy.API(auth)
              try:
                  api.update_status(message)
                  print("Tweet posted successfully!")
              except tweepy.TweepError as error:
                  print(f"Error posting tweet: {error}")

          api_key = os.environ['TWITTER_API_KEY']
          api_secret = os.environ['TWITTER_API_SECRET_KEY']
          access_token = os.environ['TWITTER_ACCESS_TOKEN']
          access_token_secret = os.environ['TWITTER_ACCESS_TOKEN_SECRET']

          remaining_days = ${{ steps.calculate_days.outputs.remaining_days }}
          tweet_message = f"🚨 Another day passed! There are {remaining_days} days remaining until the end of Ummath 2080. #Ummath #Countdown #MuslimCommunity #Faith"

          post_tweet(api_key, api_secret, access_token, access_token_secret, tweet_message)
          EOF
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
