name: Post Remaining Days of Ummath (Python)

on:
  schedule:
    - cron: '0 9 * * *'  # Run every day at 09:00 UTC
  workflow_dispatch:  # Allows manual triggering 

jobs:
  post-ummath:
    runs-on: ubuntu-latest
    env: # Set environment variables at the job level
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Install Dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          pip install tweepy

      - name: Post to Twitter
        run: python tweet.py 
        shell: /usr/bin/bash -e {0}
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.12.4/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib
