name: Post Remaining Days of Ummath (Python)

on:
  schedule:
    - cron: '0 9 * * *'  # Run every day at 09:00 UTC
  workflow_dispatch:  # Allows manual triggering 

jobs:
  post-ummath:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Or specify a specific version like '3.9'

      - name: Install Dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          pip install tweepy # Install tweepy library

      - name: Post to Twitter
        run: |
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> $GITHUB_ENV
          echo "TWITTER_API_SECRET_KEY=${{ secrets.TWITTER_API_SECRET_KEY }}" >> $GITHUB_ENV
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> $GITHUB_ENV
          python tweet.py 
